version: '3.4'

services:
  
  db:
    build:
      context: ./database
    environment:
      POSTGRES_DB: <%= databaseName %>
      POSTGRES_USER: main
      POSTGRES_PASSWORD: password
    expose:
      - 5432

  <%= serviceName %>:
    build:
      context: ./
      target: prod
    environment:
      PORT: 3000
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: <%= databaseName %>
      PGUSER: main
      PGPASSWORD: password
